# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directories:
      - "/deluge-seedbox/"
      - "/docker-proxy/"
      - "/docker-volume-rclone/"
      - "/foldingathome/"
      - "/media-server/"
      - "/netbootxyz/"
      - "/nginx-stacks/filestash/"
      - "/nginx-stacks/guacamole/"
      - "/nginx-stacks/homepage/"
      - "/nginx-stacks/nginx-proxy-manager/"
      - "/nginx-stacks/openspeedtest/"
      - "/nginx-stacks/vert-sh/"
    schedule:
      interval: "weekly"
