services:
  app:
    container_name: filestash
    image: machines/filestash@sha256:8e2f58b07efd5f88e6ade8e1bc15268fc7103183995dd28cd498ebac40a5b02e
    restart: unless-stopped
    environment:
    - APPLICATION_URL=filestash.int.saphnet.xyz
    - CANARY=true
    - OFFICE_URL=http://127.0.0.1:9980
    - OFFICE_FILESTASH_URL=http://app:8334
    # ports:
    # - "8334:8334"
    volumes:
    - filestash:/app/data/state/
    networks:
    - web_bridge

  wopi_server:
    container_name: filestash_wopi
    image: collabora/code:25.04.7.1.1
    restart: unless-stopped
    environment:
    - "extra_params=--o:ssl.enable=false"
    command:
    - /bin/bash
    - -c
    - |
         curl -o /usr/share/coolwsd/browser/dist/branding-desktop.css https://gist.githubusercontent.com/mickael-kerjean/bc1f57cd312cf04731d30185cc4e7ba2/raw/d706dcdf23c21441e5af289d871b33defc2770ea/destop.css
         /bin/su -s /bin/bash -c '/start-collabora-online.sh' cool
    user: root
    ports:
    - "9980:9980"

volumes:
  filestash:

networks:
  web_bridge:
    name: web_bridge