services:
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    ports:
      - '3000:3000'
      - '3001:3001'
    image: openspeedtest/latest:v2.0.6
    networks:
      - web_bridge

networks:
  web_bridge:
    name: web_bridge